Added support for multiplot
MrToino/lion-of-graphs pull request #49
Opened 2023-01-25 22:45 UTC by MrToino

Added support for multiplot from one single file in one same figure.

2023-01-25 22:48 UTC, MrToino commented
Still a WIP, the plotter service is ready (for a simple workflow). I will later implement the same for the fitter service.
If you have any suggestions please share.

2023-01-26 23:48 UTC, luisferreira32 requested changes
I think there should be some re-thinking on the design of the generic options for the plotting.

2023-01-26 23:48 UTC, luisferreira32 commented on services/_models/options.py
> +class FitPlot(BaseModel):
Isn't this class a duplicate from the `Plot` class?

2023-01-26 23:48 UTC, luisferreira32 commented on services/_utils/preprocessor.py
> +    return function
Yes

2023-01-26 23:48 UTC, luisferreira32 commented on services/_models/options.py
> +class Options(BaseModel):
These options lost their meaning a bit like this, and seem a bit hardcoded per the two use-cases

2023-01-26 23:48 UTC, luisferreira32 commented on services/plotter/plotter.py
> +def build_plot(data: DataFrame, options: Options, func: str, fit_data: DataFrame = None):
Got to say that this function is not the best representation of a "generic" build a plot.
You could for instance accept a list of tuples of `DataFrame` and `Options` (the old ones), and then do plotting based on that. The caller itself should be the one defining the data points to draw (and options), so if a function is coming, it's not up to the plotter to decide the number of data points.

And, if we're plotting a function, it's just treating it in the request before parsing it over here as points.`

Another note on the signature is that you spread the data frames in two arguments (data and fit_data) with the `Options` compiled for both of the data frames. In the end, you don't know what related with which, making the whole thing a bit of a spaghetti code.

2023-01-26 23:48 UTC, luisferreira32 commented on services/_models/options.py
> +class Figure(BaseModel):
Figure would not be the best naming here, as it conflicts with the matplotlib one

2023-01-26 23:52 UTC, MrToino commented on services/_models/options.py
> +class FitPlot(BaseModel):
For now it is duplicated indeed, but later on it have some differences. As we don't have yet a data model, for now we should separate things.

2023-01-26 23:52 UTC, MrToino commented on services/_utils/preprocessor.py
> +    return function
Yes, it is a TODO

2023-01-26 23:55 UTC, MrToino commented on services/_models/options.py
> +class Figure(BaseModel):
Although it doesn't conflict (as the Figure object is actually `figure`), you are right and the naming should change. This problem will disappear after we define a proper data model so that may be the next priority.

2023-01-26 23:55 UTC, MrToino commented on services/_models/options.py
> +class Options(BaseModel):
I don't understand your point. What do you suggest?

2023-01-26 23:57 UTC, MrToino commented on services/plotter/plotter.py
> +def build_plot(data: DataFrame, options: Options, func: str, fit_data: DataFrame = None):
Yes, this stills needs some work on top. But once again, I guess we now see the urge of having a good data model, so I'll be working on that as soon as possible.

2023-01-27 20:02 UTC, luisferreira32 commented on services/plotter/plotter.py
> +def build_plot(data: DataFrame, options: Options, func: str, fit_data: DataFrame = None):
In this PR I'd do a proposal (to have both cases supported with minimal effort) to have this function take two lists (that for now would have to be similar) and do something like

```
def build_plot( data [], options[] ):
   // build figure
   // for each data options pair, draw
   // save fig
```

2023-01-28 00:44 UTC, luisferreira32 commented on services/_models/options.py
> +class Options(BaseModel):
You can have actually separated options per use case, if you want them to be configured differently, and just extend the API on the server to have multiple inputs. Or, the main proposal, have like a `PlotOptions` and a `FigureOptions` that are passed on both requests (plotOptions can even be a list)

2023-01-28 00:44 UTC, luisferreira32 approved these changes
I'll leave an approve and trust your good sense of judgment later :+1:

2023-01-28 13:25 UTC, MrToino commented
I will be building a data model to have a better vision of the data workflow, and thus replicate the best possible implementation. Later on, I will require your review.

2023-02-05 10:50 UTC, MrToino commented
As discussed, there is a need to build a proper data model that can properly define the workflow. 
In this sense, we will be closing this PR and building the data model on another one.

2023-02-05 10:53 UTC, merged