Separate plotter code from fitter code
MrToino/lion-of-graphs pull request #50
Opened 2023-01-26 20:43 UTC by luisferreira32

Move common code to utility wrapper for MPB and have build plot with different requirements for different services (wip)

2023-02-06 18:13 UTC, luisferreira32 commented on services/plotter/plotter.py
> -from io import BytesIO
Most of this file was moved to the common MPB wrapper, since, in the end, we're basically waiting to use MPB in two different ways (for two different use cases) and doing a whole mixture importing one service from another. So let's leave the utility wrapper in the `_utils` folder. (feel free to propose renaming of that filename as well)

2023-02-06 18:14 UTC, luisferreira32 commented on services/plotter/plotter.py
> -        set_plots(axes, fit_data, options.fitPlots)
This IF statement is no longer needed, as this part of building should be service dependent.

2023-02-06 18:15 UTC, luisferreira32 commented
@MrToino , could you test this out with the app? I don't have my main setup with me, so coding was done a bit ad-hoc as well

2023-02-06 19:01 UTC, MrToino requested changes
Some changes are required to proceed. Please check the review.

2023-02-14 09:43 UTC, MrToino commented
I think you should implement the requested changes and close this PR since we will build a data model to better define the workflow at #51.

2023-02-16 23:39 UTC, luisferreira32 commented on services/plotter/service.py
> +    uid = uuid4()
Fair point, we can change in a follow-up PR to do the whole thing a HTTP call?

2023-02-17 19:04 UTC, MrToino approved these changes
Approved

2023-02-17 22:03 UTC, merged